### ISSUE TITLE
Error: 500

### ISSUE THREAD

**Issue by douglasmiguel** [ibrotzky/visabot#1]
payload: {"question":43,"name":"Douglas Miguel","married":true,"spouseCanadianCitizen":false,"spouseCommingAlong":true,"age":30,"educationLevel":4,"canadianDegreeDiplomaCertificate":false,"firstLanguageTest":"0","firstLanguageSpeaking":9,"firstLanguageListening":10,"firstLanguageReading":11,"firstLanguageWriting":8,"workExperienceInCanada":"0","workExperienceLastTenYears":3,"certificateQualificationProvince":false,"validJobOffer":false,"nominationCertificate":false,"spouseAge":30,"spouseEducationLevel":1,"spouseCanadianDegreeDiplomaCertificate":false,"spouseFirstLanguageTest":2,"spouseFirstLanguageSpeaking":10,"spouseFirstLanguageListening":10,"spouseFirstLanguageReading":10,"spouseFirstLanguageWriting":10,"spouseSecondLanguageTest":1,"spouseSecondLanguageSpeaking":10,"spouseSecondLanguageListening":10,"spouseSecondLanguageReading":10,"spouseSecondLanguageWriting":10,"spouseWorkExperienceInCanada":"0","spouseWorkExperienceLastTenYears":3,"spouseCertificateQualificationProvince":false,"spouseValidJobOffer":false}

Whenever I get into this question the application starts to return error 500:
Does your spouse or common-law partner have a nomination certificate from a province or territory?

![screen shot 2017-01-05 at 19 41 21](https://cloud.githubusercontent.com/assets/299119/21698633/fa278762-d37e-11e6-8f13-aba399dc7f32.png)

**Comment by bvpmiranda** [comment]
Fixed douglasmiguel. Thanks for the feedback
