### ISSUE TITLE
Express Entry score - Add the avarege score to be accepted

### ISSUE THREAD

**Issue by MiattoRocha** [ibrotzky/visabot#3]
Hi there,
Congratulations about this project, it's a awesome idea and will help all developers that want to immigrate.

The official site of Canadian Government has a information about the lowest score invited, my suggest is add this in the final report about Express Entry.

**Comment by bvpmiranda** [comment]
It's in the roadmap to do something with that information, but we don't just want to show the last score, we want to interpret the last scores to give a more educated information to the user.

Thanks for the input.
